### PR TITLE
fix(79875028): get up to date actor image

### LINKED ISSUE #143: Actor Image is to old
**Describe the bug**
Cause the image for an actor changed on wikipedia, the saved link doesnt show an image anmore.

**To Reproduce**
http://localhost:5077/actor/Tom%20Hanks

**Expected behavior**
Please check somehow if an image is shown (without making a second request) and if its the placeholder image, update the image. 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Maxiboy441**

### CODE REVIEW

File: Project/Project/Controllers/ActorController.cs [hunk 1]
```diff
@@ -38,5 +50,21 @@ public async Task<IActionResult> Show(string name)
...
+        using (HttpClient client = new HttpClient())
+        {
+            try
+            {
+                HttpResponseMessage response = await client.GetAsync(url);
+                return response.StatusCode == System.Net.HttpStatusCode.OK;
+            }
+            catch (Exception ex)
+            {
+                Console.WriteLine($"An error occurred: {ex.Message}");
```
Comment (feliperamoss) [inline Project/Project/Controllers/ActorController.cs]: Please remove Console
```suggestion
```

File: Project/Project/Controllers/ActorController.cs [hunk 2]
```diff
@@ -38,5 +50,21 @@ public async Task<IActionResult> Show(string name)
...
+                return false; // Return false if there's an error
```
Comment (feliperamoss) [inline Project/Project/Controllers/ActorController.cs]:
```suggestion
                return false;
```
