### PR TITLE
Recommendations not ideal

### LINKED ISSUE #129: Not Ideal Recommendation
**Describe the bug**
Recommendations are sometimes only 2 and also sometimes duplicates of the other lists.

**To Reproduce**
- get recommendaions

**Expected behavior**
There should be more and new discovered movies as recommendations.

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by Maxiboy441**
…et more on next login.

### CODE REVIEW

File: Project/Project/Controllers/AuthController.cs [hunk 1]
```diff
@@ -63,9 +63,10 @@ public async Task<IActionResult> Login(LoginViewModel model, string returnUrl =
             var newestRecommendationDate = await _recommendationService.GetNewestRecommendationDate(userId);
             var favorites = await _recommendationService.GetFavorites(userId);
             var ratings = await _recommendationService.GetLikedMovies(userId);
+            var recommendationCount = await _context.Recommendations.CountAsync(r => r.User_id == userId);
             
             if ((favorites.Any() || ratings.Any()) &&
-                (newestRecommendationDate == null || newestRecommendationDate < DateTime.Now.AddDays(-7)))
+                ((newestRecommendationDate == null || newestRecommendationDate < DateTime.Now.AddDays(-7)) || recommendationCount < 5 ))
```
Comment (feliperamoss) [inline Project/Project/Controllers/AuthController.cs:69]: I think this is not working properly. First i got these recommendations, which is ok:
image

and then on my next login, as i had less than 5 recommendations i got new ones, but i got duplicate recommendations, like The Dark Knight Rises and Black Panther
image

Comment (Maxiboy441) [reply Project/Project/Controllers/AuthController.cs:69]: Couldnt replicate you error but made sure you dont get duplicate now, the amount on second try is fine (if less than 4 then request new ones, no 13 at max now)
